### ISSUE TITLE
Make ProtoBuf thread safe

### ISSUE THREAD

**Issue by tanmaykm** [JuliaIO/ProtoBuf.jl#140]
ProtoBuf currently holds state related to struct metadata and field population data in global dictionaries [here](https://github.com/JuliaIO/ProtoBuf.jl/blob/06a932a795a1676c39513a29b1be56a465cf8514/src/codec.jl#L534-L536) which are not thread safe.

They can instead be moved into the generated struct itself and `getproperty`, `setproperty`, `hasproperty` methods should be used to expose them. We may need to move the lowerbound of supported Julia version to 1.2.

**Comment by PhilipVinc** [comment]
I realised that if we protect adding new elements to the caches, in particular `_fillcache`, with a threaded-lock prevents the bug reported in `TensorBoardLogger`.

in codec.jl
```
const _metacache_lock = ReentrantLock()
const _mapentry_lock  = ReentrantLock()
const _fillcache_lock = ReentrantLock()
```

and then see [this commit](https://github.com/JuliaIO/ProtoBuf.jl/commit/6e4693ae13f27f7812a2deaa394a0f0cf6581079).
This commit would allow for creating ProtoBuf objects among multiple threads by paying the cost of locking a ReentrantLock every time we create/destroy one of those objects. However it will not allow to modify a single ProtoBuf object from multiple threads at the same time.

I am not sure about the performance cost of this... what do you think?

cc @jbaron @oxinabox

**Comment by jbaron** [comment]
Would be very helpful. P.S I know it is not considered best practice, but quickly glancing at the change you could get away with a spinlock which could have less overhead.

**Comment by PhilipVinc** [comment]
I tried that, but using a spinlock had the following issue:
 - If you Ctrl-C while the lock is held, the global const is left in a bad state, so unless you reinitialise the locks the program will most likely not work anymore. Probably fixable but unsure how.

I'm unsure why this does not manifest itself with a Reentraant lock. I'd expect it to also be present there.

**Comment by jbaron** [comment]
Possible you could avoid that with the try/finally clause so that the unlock is guarantee to be executed, but perhaps that makes it also slower again.  For my use-case the performance implications are not that big, so fine with either solutions.

**Comment by oxinabox** [comment]
You don't want to use a `SpinLock` anyway, it is a worse lock for most use cases. Or so I am told.

The option instead of a lock is to just stop caching these things, and just regenerate each time.
Which is worth timing, `Dict` lookup is often not that fast in the grand scheme of things.

But in general i think the performance of something that happens along side an IO operation is probably not to be worried about, the IO will dominate.

**Comment by jbaron** [comment]
Just out of curiosity, it the Julia SpinLock not the same as the one used by the Linux kernel? Because in that case it would avoid a context switch and as long as you acquire the lock for a short period of time and don't lock all cores/threads at once, it can be efficient (like a kind of busy loop).
