### ISSUE TITLE
feature: hope add format for generated *_pb.jl

### ISSUE THREAD

**Issue by zsz00** [JuliaIO/ProtoBuf.jl#206]
hope add format for generated *_pb.jl

![image](https://user-images.githubusercontent.com/12711073/185421662-11470e1c-7458-4ba6-bf79-9fbd63ed4cbf.png)

**Comment by Drvi** [comment]
I tried making the generated metadata methods having one field per line, but the files got really long because of that. I think if one wants to *read* the metadata, they should look at the proto files directly, and use these generated methods only when the need to programmatically access their values.

As a workaround, you can install `JuliaFormatter` and format the whole output directory of translated julia files.

**Comment by zsz00** [comment]
I update the picture :
![image](https://user-images.githubusercontent.com/12711073/185426701-fd64f9ef-8194-4776-9c29-c97bd508be35.png)
export .....   to long

ok, I can format the whole output directory *.jl use JuliaFormatter.

**Comment by Drvi** [comment]
Yeah, for exports it kinda makes sense to have them presented in a readable way... Want to contribute?:) These lines print the export statement: https://github.com/JuliaIO/ProtoBuf.jl/blob/v1.0.2/src/codegen/toplevel_definitions.jl#L180-L185 

I think I a case like this we want multiple lines starting with `export`keyword and all of them shorter than 92 characters, a la second example in the [Blue Style](https://github.com/invenia/BlueStyle#function-exports)

**Comment by zsz00** [comment]
OK, Let me try do this

**Comment by zsz00** [comment]
#207

**Comment by Drvi** [comment]
Closed via #207 and #210
